create table if not exists public.feedback_entries (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null default '',
  rating smallint not null check (rating between 1 and 5),
  message text not null,
  created_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.feedback_entries enable row level security;

drop policy if exists "feedback_entries_block_public_reads" on public.feedback_entries;
drop policy if exists "feedback_entries_block_public_writes" on public.feedback_entries;

create policy "feedback_entries_block_public_reads"
on public.feedback_entries
for select
to anon, authenticated
using (false);

create policy "feedback_entries_block_public_writes"
on public.feedback_entries
for insert
to anon, authenticated
with check (false);
